[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Serial Monitor & Upload Options
monitor_speed = 115200
upload_speed = 921600
upload_port = COM5
monitor_port = COM5

; CPU & Flash Configuration
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = dio
board_build.filesystem = littlefs

; External Dependencies
lib_deps = 
    https://github.com/lvgl/lvgl.git#v8.3.3
    bblanchon/ArduinoJson@6.21.4

; Compiler Flags & Include Paths
build_flags = 
    -D LV_CONF_INCLUDE_SIMPLE
    -D CORE_DEBUG_LEVEL=3
    -I include
    -O2
    -Wall
    -D TFT_MISO=12
    -D TFT_MOSI=13
    -D TFT_SCLK=14
    -D TFT_CS=15
    -D TFT_DC=2
    -D TFT_RST=-1
    -D TFT_BL=27
    -D TOUCH_CS=33
